### ISSUE TITLE
Plans for support eevee?

### ISSUE THREAD

**Issue by nafergo** [AO-StreetArt/BlenderQ#1]
This is a great tool :)
Any plans for support eevee?

**Comment by AO-StreetArt** [comment]
Thanks for your interest!

The tool should already support Eevee rendering, actually.

If you look in the config.ini file in the repo, you'll see an option 'blender.hidden_ops'.

By default, this is set to '--engine CYCLES --use-extension 1 -b'.  Change this to '--engine BLENDER_EEVEE --use-extension 1 -b', then restart BlenderQ.

Using this configuration setting, you can switch back and forth to any engine available in the Blender version you are working with.

If you run into any issues working with this, please raise a defect and I'll be happy to address it!

**Comment by nafergo** [comment]
Tested and  all seems fine! :+1:
