### ISSUE TITLE
Can't run BlenderQ on Windows 10

### ISSUE THREAD

**Issue by nafergo** [AO-StreetArt/BlenderQ#2]
Tried to debug and fix it but I don't know python so it's something that I cannot really fix...

```
First error is:
Traceback (most recent call last):
  File "blenderq.py", line 25, in <module>
    from Tkinter import Tk
ModuleNotFoundError: No module named 'Tkinter'

```

So I renamed to tkinter and it goes forward but then...

```
Traceback (most recent call last):
  File "blenderq.py", line 29, in <module>
    from src.BlenderQFrame import BlenderQFrame
  File "C:\Users\campi\Desktop\BlenderQ-master\src\BlenderQFrame.py", line 26, in <module>
    from ttk import Frame, Button, Style, Label, Entry
ModuleNotFoundError: No module named 'ttk'
```

I actually went a bit further but then some errors come out related to self
so it' not just renaming stuff and capital letters :)

**Comment by AO-StreetArt** [comment]
I apologize for the late reply, been a hectic few weeks.  It looks to me like you're using Python3, and not Python2.  I think there is some additional work to migrate this to support Python3.  Please give it a shot with Python2 for now, and I need to do the migration before Jan 1, 2020 at a minimum, so this is definately on my radar.

**Comment by nafergo** [comment]
Thx for the reply! My usual workmachine is running just fine on ubuntu :) I'll try again as soon as I have some time with my coworker windows desktop. ;)
